/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.fabianodarolt.pousada.view1;

import br.com.fabianodarolt.pousada.Controller.FuncionarioController;
import br.com.fabianodarolt.pousada.Model.Funcionario;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fabiano
 */
public class FuncionarioLista extends javax.swing.JFrame {

    private JTable tabela;
    private int linhaSelecionada;
    private DefaultTableModel modelo = new DefaultTableModel();

    /**
     * Creates new form FuncionarioLista
     */
    public FuncionarioLista() {
        initComponents();
        criaJTable();
        painelRolagem.setViewportView(tabela);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        painelConsulta = new javax.swing.JPanel();
        txPesquisar = new javax.swing.JTextField();
        btPesquisar = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();
        btEliminar = new javax.swing.JButton();
        painelRolagem = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.BorderLayout());

        painelConsulta.setBackground(new java.awt.Color(204, 204, 204));
        painelConsulta.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Consulta de Funcionário", 0, 0, new java.awt.Font("Arial Black", 0, 14))); // NOI18N
        painelConsulta.setLayout(null);

        txPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txPesquisarActionPerformed(evt);
            }
        });
        painelConsulta.add(txPesquisar);
        txPesquisar.setBounds(270, 70, 250, 20);

        btPesquisar.setText("Pesquisar");
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });
        painelConsulta.add(btPesquisar);
        btPesquisar.setBounds(540, 70, 85, 23);

        btEditar.setText("Editar");
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });
        painelConsulta.add(btEditar);
        btEditar.setBounds(437, 106, 85, 23);

        btEliminar.setText("Eliminar");
        btEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliminarActionPerformed(evt);
            }
        });
        painelConsulta.add(btEliminar);
        btEliminar.setBounds(540, 106, 85, 23);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
            .addComponent(painelRolagem)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(painelConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelRolagem, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        //        TODO add your handling code here:
        int linhaSelecionada = -1;
        linhaSelecionada = tabela.getSelectedRow();
        if (linhaSelecionada >= 0) {
            int idFuncionario = (int) tabela.getValueAt(linhaSelecionada, 0);
            
            FuncionarioCadastro f1 = new FuncionarioCadastro(modelo,linhaSelecionada,idFuncionario);
            f1.setLocation(null);
            f1.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Nenhuma linha Selecionada");

        }
    }//GEN-LAST:event_btEditarActionPerformed

    private void btEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliminarActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = -1;
        linhaSelecionada = tabela.getSelectedRow();
        if (linhaSelecionada >= 0) {
            int idFuncionario = (int) tabela.getValueAt(linhaSelecionada, 0);
            FuncionarioController fc = new FuncionarioController();
            if (fc.remove(idFuncionario)) {
                modelo.removeRow(linhaSelecionada);
            } else {
                JOptionPane.showMessageDialog(null, "Nenhuma Linha Selecionada");
            }
        }
    }//GEN-LAST:event_btEliminarActionPerformed

    private void txPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txPesquisarActionPerformed
        // TODO add your handling code here:
         String nome = txPesquisar.getText();
        FuncionarioController uc = new FuncionarioController();
        uc.listByNome(nome);
        //metodo par alimpar tabela
        modelo.setNumRows(0);
        for (Funcionario f : uc.listByNome(nome)) {
            modelo.addRow(new Object[]{
                f.getId(),
                f.getNome(),
                f.getLogin(),
                f.getCpf(),
                f.getTelefoneResindecial(),
                f.getSexo()});
        }      
    }//GEN-LAST:event_txPesquisarActionPerformed

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btPesquisarActionPerformed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btEliminar;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel painelConsulta;
    private javax.swing.JScrollPane painelRolagem;
    private javax.swing.JTextField txPesquisar;
    // End of variables declaration//GEN-END:variables

//    private void criaJTable() {
//        tabela = new JTable(modelo);
//        modelo.addColumn("Código");
//        modelo.addColumn("Nome");
//        modelo.addColumn("CPF");
//        modelo.addColumn("Telefone");
//        modelo.addColumn("Sexo");
//        modelo.addColumn("Usuário");
//        preencherJTable();
//    }
//
//    private void preencherJTable() {
//        FuncionarioController uc = new FuncionarioController();
//        for (Funcionario f : uc.listarTodos()) {
//            modelo.addRow(new Object[]{
//                f.getId(),
//                f.getNome(),
//                f.getSexo(),
//                f.getDataNascimento(),
//                f.getRg(),
//                f.getCpf(),
//                f.getEndereco().getIdEndereco(),
//                f.getEndereco().getRua(),
//                f.getEndereco().getNumero(),
//                f.getEndereco().getComplemento(),
//                f.getEndereco().getBairro(),
//                f.getEndereco().getCidade(),
//                f.getEndereco().getEstado(),
//                f.getEndereco().getPais(),
//                f.getEndereco().getCep(),
//                f.getTelefoneResindecial(),
//                f.getTelefoneCelular(),
//                f.getEmail(),
//                f.getSalario(),
//                f.getDataAdmissao(),
//                f.getFuncao(),
//                f.getLogin(),
//                f.getSenha()});
//        }
//    }

    private void criaJTable() {

        tabela = new JTable(modelo);
        modelo.addColumn("Código");
        modelo.addColumn("Nome");
        modelo.addColumn("CPF");
        modelo.addColumn("Telefone");
        modelo.addColumn("Sexo");
        modelo.addColumn("Usuário");
        preencherJTable();
    }

    private void preencherJTable() {

        FuncionarioController uc = new FuncionarioController();
        for (Funcionario f : uc.listarTodos()) {
            modelo.addRow(new Object[]{
                f.getId(),
                f.getNome(),
                f.getSexo(),
                f.getDataNascimento(),
                f.getTelefoneResindecial()
            });
        }
    }
}